# Generated by Django 3.2.8 on 2021-11-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rates',
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='user',
            name='rate_counts',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rate_points',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
