# Generated by Django 3.2.8 on 2021-11-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vip_expire',
            new_name='subscription_expire',
        ),
    ]
