# Generated by Django 3.2.8 on 2021-11-02 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='UUID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
                ('slug_title', models.SlugField(allow_unicode=True, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('share_qty', models.BigIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bookmarks', models.ManyToManyField(related_name='article_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='article_likes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.article')),
            ],
        ),
    ]
