# Generated by Django 3.2.8 on 2021-11-02 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='parent',
        ),
        migrations.AddField(
            model_name='article',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug_title',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
