# Generated by Django 3.2.8 on 2021-11-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211102_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='org',
            new_name='parent',
        ),
    ]
