# Generated by Django 3.2.8 on 2021-10-25 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211025_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug_title',
        ),
        migrations.AddField(
            model_name='article',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='UUID'),
        ),
    ]
