# Generated by Django 3.2.8 on 2021-10-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211025_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug_title',
            field=models.SlugField(allow_unicode=True, default='feop', unique=True),
            preserve_default=False,
        ),
    ]
