# Generated by Django 3.2.8 on 2021-10-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_slug_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug_title',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
