# Generated by Django 3.2.8 on 2021-11-09 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='article',
            name='rate_counts',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='rate_points',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='article_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='article_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
