# Generated by Django 3.2.8 on 2021-11-13 13:01

from django.db import migrations, models
import extensions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_course_mediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, validators=[extensions.validators.FutureDateValidator()], verbose_name='Deadline'),
        ),
    ]
