# Generated by Django 3.2.8 on 2021-11-15 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_auto_20211115_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, null=True, related_name='article_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
