# Generated by Django 3.2.8 on 2021-11-21 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_auto_20211117_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.AddField(
            model_name='article',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='users_bookmarked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='users_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
