# Generated by Django 3.2.8 on 2021-11-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20211121_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='article',
            name='rate_counts',
        ),
        migrations.RemoveField(
            model_name='article',
            name='rate_points',
        ),
    ]
