# Generated by Django 3.2.8 on 2021-11-16 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0014_auto_20211115_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['course', 'article']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
