# Generated by Django 3.2.8 on 2021-11-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20211122_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Published')], default=1),
        ),
    ]
