# Generated by Django 3.2.8 on 2021-11-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20211122_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
