# Generated by Django 3.2.8 on 2021-10-26 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211026_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.AddField(
            model_name='user',
            name='bookmarked_by',
            field=models.ManyToManyField(related_name='user_bookmarked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_by',
            field=models.ManyToManyField(related_name='user_liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
