# Generated by Django 3.2.8 on 2021-10-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20211026_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='shares',
            new_name='share_qty',
        ),
    ]
