# Generated by Django 3.2.8 on 2021-10-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_shares_user_share_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_img',
            field=models.ImageField(upload_to='images/users/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_img',
            field=models.ImageField(upload_to='images/users/covers/'),
        ),
    ]
