# Generated by Django 3.2.8 on 2021-10-31 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20211030_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmarked_by',
            field=models.ManyToManyField(related_name='bookmarked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(choices=[(1, 'آذربایجان شرقی'), (2, 'آذربایجان غربی'), (3, 'اردبیل'), (4, 'اصفهان'), (5, 'البرز'), (6, 'ایلام'), (7, 'بوشهر'), (8, 'تهران'), (9, 'چهارمحال و بختیاری'), (10, 'خراسان جنوبی'), (11, 'خراسان رضوی'), (12, 'خراسان شمالی'), (13, 'خوزستان'), (14, 'زنجان'), (15, 'سمنان'), (16, 'سیستان و بلوچستان'), (17, 'فارس'), (18, 'قزوین'), (19, 'قم'), (20, 'کردستان'), (21, 'کرمان'), (22, 'کرمانشاه'), (23, 'کهگیلویه و بویراحمد'), (24, 'گلستان'), (25, 'لرستان'), (26, 'گیلان'), (27, 'مازندران'), (28, 'مرکزی'), (29, 'هرمزگان'), (30, 'همدان'), (31, 'یزد')], default='تهران', max_length=30),
        ),
    ]
